---
title: "Detailed Guide"
author: "Jeremy Gillard"
date: "Last update `r format(Sys.time(), '%d/%m/%Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    css: styles.css
vignette: >
  %\VignetteIndexEntry{Detailed Guide}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(width = 300)
```

# Data Selection, Dataframe Unit Construction

Assuming that the following dataframe is what you initially have at your disposal.

```{r}
library(somar)
df <- somar::experimental_data.df
str(df)
```

In order to be displayed in a graph, the dataframe informations must first be correctly selected and filtered.

```{r}
metaframe <- separate_data(df, "\\_[A-z]+\\_", inverse = TRUE)
dataframe <- separate_data(df, "\\_[A-z]+\\_")

params <- prefix_vector(dataframe, "_")
params_dataframes_list <- list()
for (param in params) {
  params_dataframes_list[[param]] <- separate_data(dataframe, paste("^", param, sep=""))
}
```

This gives us in this case 4 dataframe.

```{r}
metaframe
```

```{r}
params_dataframes_list
```

After that it can be interesting to gather the R, CI and P data according to the metadata.

```{r}
dataframe_units <- list()
nrow(metaframe)
```
